// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sziminihcsrdmzuobvrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6aW1pbmloY3NyZG16dW9idnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTIyNDYsImV4cCI6MjA2MDQ2ODI0Nn0.uzsCCayqEQSZwqiqsfRBBr5lubMJSrBhSbEUVc8PfSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);